# Schema for the configuration files of the OpenID Connect module.

openid_connect.settings:
  type: config_object
  label: 'OpenID Connect settings'
  mapping:
    always_save_userinfo:
      type: boolean
      label: 'Save user claims on every login'
    connect_existing_users:
      type: boolean
      label: 'Automatically connect existing users'
    override_registration_settings:
      type: boolean
      label: 'Override registration settings'
    userinfo_mappings:
      type: mapping
      label: 'OpenID Connect settings'
      mapping:
        timezone:
          type: string
          label: 'Timezone'
        picture:
          type: string
          label: 'Picture'

openid_connect.settings.facebook:
  type: config_object
  label: 'OpenID Connect Facebook settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        api_version:
          type: string
          label: 'API Version'

openid_connect.settings.generic:
  type: config_object
  label: 'OpenID Connect Generic settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        authorization_endpoint:
          type: string
          label: 'Authorization endpoint'
        token_endpoint:
          type: string
          label: 'Token endpoint'
        userinfo_endpoint:
          type: string
          label: 'Userinfo endpoint'

openid_connect.settings.github:
  type: config_object
  label: 'OpenID Connect GitHub settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'

openid_connect.settings.google:
  type: config_object
  label: 'OpenID Connect Google settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'

openid_connect.settings.linkedin:
  type: config_object
  label: 'OpenID Connect LinkedIn settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
